name: xorProject
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.29.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libcxx=19.1.3
  - libedit=3.1.20191231
  - libffi=3.4.4
  - libsodium=1.0.20
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.4.0
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.10.15
  - python-dateutil=2.9.0.post0
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - ai21==3.0.0
      - ai21-tokenizer==0.12.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.11.7
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anthropic==0.39.0
      - anyio==4.6.2.post1
      - argparse==1.4.0
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - attrs==24.2.0
      - beautifulsoup4==4.12.3
      - bs4==0.0.2
      - cachetools==5.5.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.0
      - chex==0.1.87
      - click==8.1.7
      - cohere==5.11.4
      - contourpy==1.3.1
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - deap==1.4.1
      - deprecated==1.2.15
      - dirtyjson==1.0.8
      - distro==1.9.0
      - docx2txt==0.8
      - etils==1.10.0
      - fastavro==1.9.7
      - filelock==3.16.1
      - filetype==1.2.0
      - flatbuffers==24.3.25
      - flax==0.10.2
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - gast==0.6.0
      - google-ai-generativelanguage==0.6.10
      - google-api-core==2.23.0
      - google-api-python-client==2.154.0
      - google-auth==2.36.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.3
      - google-pasta==0.2.0
      - googleapis-common-protos==1.66.0
      - greenlet==3.1.1
      - grpcio==1.68.0
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.7
      - httplib2==0.22.0
      - httpx==0.27.2
      - httpx-sse==0.4.0
      - huggingface-hub==0.26.2
      - humanize==4.11.0
      - idna==3.10
      - importlib-resources==6.4.5
      - jinja2==3.1.4
      - jiter==0.7.1
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - keras==3.6.0
      - kiwisolver==1.4.7
      - langchain==0.3.8
      - langchain-community==0.3.8
      - langchain-core==0.3.21
      - langchain-openai==0.2.9
      - langchain-text-splitters==0.3.2
      - langsmith==0.1.145
      - libclang==18.1.1
      - litellm==1.52.14
      - llama-cloud==0.1.5
      - llama-index==0.12.1
      - llama-index-agent-openai==0.4.0
      - llama-index-cli==0.4.0
      - llama-index-core==0.12.1
      - llama-index-embeddings-openai==0.3.0
      - llama-index-indices-managed-llama-cloud==0.6.2
      - llama-index-legacy==0.9.48.post4
      - llama-index-llms-litellm==0.3.0
      - llama-index-llms-openai==0.3.1
      - llama-index-llms-openai-like==0.3.0
      - llama-index-multi-modal-llms-openai==0.3.0
      - llama-index-program-openai==0.3.0
      - llama-index-question-gen-openai==0.3.0
      - llama-index-readers-file==0.4.0
      - llama-index-readers-llama-parse==0.4.0
      - llama-parse==0.5.15
      - lxml==5.3.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.23.1
      - matplotlib==3.9.3
      - mdurl==0.1.2
      - memory-profiler==0.61.0
      - ml-dtypes~=0.3.1
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - namex==0.0.8
      - networkx==3.4.2
      - nltk==3.9.1
      - numpy==1.26.4
      - openai==1.54.5
      - opt-einsum==3.4.0
      - optax==0.2.4
      - optree==0.13.1
      - orbax-checkpoint==0.10.1
      - orjson==3.10.12
      - pandas==2.2.3
      - parameterized==0.9.0
      - pdfminer==20191125
      - pillow==11.0.0
      - pip==24.3.1
      - playsound==1.3.0
      - propcache==0.2.0
      - proto-plus==1.25.0
      - protobuf==4.25.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pycryptodome==3.21.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydantic-settings==2.6.1
      - pyparsing==3.2.0
      - pypdf==5.1.0
      - pypdf2==3.0.1
      - python-dotenv==1.0.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rpds-py==0.21.0
      - rsa==4.9
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - sentence-transformers==3.3.1
      - sentencepiece==0.2.0
      - simplejson==3.19.3
      - sniffio==1.3.1
      - sounddevice==0.5.1
      - soupsieve==2.6
      - sqlalchemy==2.0.35
      - striprtf==0.0.26
      - sympy==1.13.1
      - tenacity==8.5.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.2
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorstore==0.1.68
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tiktoken==0.8.0
      - tokenizers==0.20.3
      - toolz==1.0.0
      - torch
      - torchvision
      - tqdm==4.67.0
      - transformers==4.46.3
      - types-requests==2.32.0.20241016
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - uritemplate==4.1.1
      - urllib3==2.2.3
      - werkzeug==3.1.3
      - wrapt==1.17.0

