name: xorProject
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip:
      - deap
      - tensorflow[and-cuda]==2.18.0
      - matplotlib
      - numpy
      - pandas
      - scikit-learn
      - pympler
      - pyyaml
      - psutil
      - seaborn