# Genetic Algorithm Parameters
ga:
  population_size: 20
  cxpb: 0.5
  mutpb: 0.2
  ngen: 20
  n_processes: 10
  max_time_per_ind: 60
  epochs: 10

# Model Parameters
model:
  hl1: 2
  hl2: 3
  activation: "relu"
  optimizer: "adam"
  lr: 0.001
  batch_size: 64
