# Genetic Algorithm Parameters
ga:
  population_size: 40
  cxpb: 0.5
  mutpb: 0.2
  ngen: 50
  n_processes: 1
  max_time_per_ind: 60
  epochs: 10

# Model Parameters
model:
  hl1: 2
  hl2: 1
  activation: "relu"
  optimizer: "adam"
  lr: 0.001
  batch_size: 64
  