# Genetic Algorithm Parameters
ga:
  population_size: 20
  cxpb: 0.5
  mutpb: 0.2
  ngen: 50
  n_processes: 1

# Model Parameters
model:
  hl1: 2
  hl2: 3
  activation: "relu"
  optimizer: "adam"
  lr: 0.001
  batch_size: 64
