# Genetic Algorithm Parameters
ga:
  population_size: 5
  cxpb: 0.5
  mutpb: 0.2
  ngen: 4
  n_processes: 5

# Model Parameters
model:
  hl1: 2
  hl2: 2
  activation: "relu"
  optimizer: "adam"
  lr: 0.001
  batch_size: 32
