# Genetic Algorithm Parameters
ga:
  population_size: 40
  cxpb: 0.5
  mutpb: 0.2
  ngen: 50
  n_processes: 1

# Model Parameters
model:
  hl1: 20
  hl2: 30
  activation: "relu"
  optimizer: "adam"
  lr: 0.001
  batch_size: 64
# 358   7655.0 MiB      0.0 MiB           1           return (val_accuracy,)
