# Genetic Algorithm Parameters
ga:
  population_size: 1000
  cxpb: 0.5
  mutpb: 0.2
  ngen: 20
  n_processes: 10
  max_time_per_ind: 300
  epochs: int 10

# Model Parameters
model:
  hl1: 20
  hl2: 30
  activation: "relu"
  optimizer: "adam"
  lr: 0.001
  batch_size: 64
# 377   1333.8 MiB      0.0 MiB           1           return (val_accuracy,)
