# Genetic Algorithm Parameters
ga:
  population_size: 4
  cxpb: 0.5
  mutpb: 0.2
  ngen: 50
  n_processes: 10
  epochs: 10
  max_time_per_ind: 600

# Model Parameters
model:
  hidden_layers: [20,30]  # Example with 3 hidden layers
  activation: "relu"
  optimizer: "adam"
  lr: 0.001
  batch_size: 64
# 4477.7 MiB      0.0 MiB           1           return (val_accuracy,)
